hosts: [@SERVER.HOST@]
port: @SERVER.PORT@
#username: admin
#password: admin
connectionPool: {
  maxContentLength: 10485760
#  enableSsl: true,
#  sslEnabledProtocols: [TLSv1.2]
  }
#serializer: {className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0,
#             config: {#serializeResultToString: true,
#                      ioRegistries: [#org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3d0,
#                                     org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry]}}
serializer: {className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
             config: {serializeResultToString: false,
                      ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3,
                                     org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry]}}
                                              